--- 
title: "Time-uncertain data analysis in R"
author: "Nick McKay"
date: "Last updated: `r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: linkedearth/time-uncertain-data-analysis-in-R
description: "This book covers time-uncertain data analysis in R, primarily relying on the geoChronR package"
---

# Welcome!

<br>

Quantifying age uncertainties is a critical component of the paleosciences (paleoclimatology, paleoecology, paleontology), and one that has become commonplace in these fields this century. However, propagating these uncertainties through subsequent analysis and assessing their impact on the conclusions of a study remains rare.  This book describes the theory and practice of time-uncertain data analysis in R, largely relying on the geoChronR package. geoChronR is an integrated framework that allows scientists to generate state-of-the-art age models for their records, create time-uncertain ensembles of their data, analyze those ensembles with a number of commonly-used techniques, and visualize their results in an intuitive way. 

A peer-reviewed paper describing geoChronR was published in March 2021 in Geochronology, [check it out here](https://doi.org/10.5194/gchron-3-149-2021)

This book, geoChronR, and other [LinkedEarth](http://linked.earth) tools are under steady development, and rely on input from and contributions from the community. If you have suggestions, requests, or would like to contribute to development, we'd love to get you more involved!


<br>


